name: Events Repository
description: Manage events within a repository
author: deniz.blue

branding:
  icon: calendar
  color: yellow

inputs:
  node-version:
    description: The Node.js version to use
    required: false
    default: '24'
  events-path:
    description: The root folder where events are stored
    required: true
    default: "./events"
  env:
    description: Environment variables to supply

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
    - shell: bash
      run: npm exec -p github:openevnt/evnt#path:packages/dev -p tsx -- tsx ./node_modules/@evnt/dev/src/cli.ts static build
      env: ${{ inputs.env }}
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
