name: Events Repository
description: Manage events within a repository
author: deniz.blue

branding:
  icon: calendar
  color: yellow

inputs:
  node-version:
    description: The Node.js version to use
    required: false
    default: '24'
  events-path:
    description: The root folder where events are stored
    required: true
    default: "./events"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
          version: latest
    - shell: bash
      run: git clone https://github.com/openevnt/evnt.git /tmp/openevnt
    - shell: bash
      working-directory: /tmp/openevnt
      run: pnpm install --frozen-lockfile
    - shell: bash
      run: pnpx tsx /tmp/openevnt/packages/dev/src/cli.ts
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
